name: Test example usage in docker build

on:
  push:
    paths:
      - .github/workflows/test_docker.yml
      - examples/**/Dockerfile
  pull_request:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Build devcontainer image to use as base
        id: devcontainer
        uses: docker/build-push-action@8c1e8f8e5bf845ba3773a14f3967965548a2341e
        with:
          context: ./.devcontainer
          push: false
          load: true
          tags: snaggle_devcontainer

      - name: Build snaggle docker image
        id: snaggle
        uses: docker/build-push-action@8c1e8f8e5bf845ba3773a14f3967965548a2341e
        with:
          context: .
          push: false
          load: true
          tags: ghcr.io/musicalninjadad/snaggle:latest

      - name: Test build the nginx example
        uses: docker/build-push-action@8c1e8f8e5bf845ba3773a14f3967965548a2341e
        with:
          context: ./examples/nginx/
          push: false
          load: true
          tags: ng

      - name: Test run nginx example
        run: docker run -d -p8000:8000 ng && curl 127.0.0.1:8000

      - name: Test build the hello world example
        uses: docker/build-push-action@8c1e8f8e5bf845ba3773a14f3967965548a2341e
        with:
          context: ./examples/hello/
          push: false
          load: true
          tags: hello

      - name: Test run hello world example
        run: docker run hello | grep ^hello$
