name: Test usage in docker build

on:
  pull_request:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Build devcontainer image to use as base
        id: devcontainer
        uses: docker/build-push-action@9e436ba9f2d7bcd1d038c8e55d039d37896ddc5d
        with:
          context: ./.devcontainer
          push: false
          load: true
          tags: snaggle_devcontainer

      - name: Build snaggle docker image
        id: snaggle
        uses: docker/build-push-action@9e436ba9f2d7bcd1d038c8e55d039d37896ddc5d
        with:
          context: .
          push: false
          load: true
          tags:
            snaggle
            ghcr.io/musicalninjadad/snaggle:latest

      - name: Build test docker image
        id: test_image
        uses: docker/build-push-action@9e436ba9f2d7bcd1d038c8e55d039d37896ddc5d
        with:
          context: .
          file: test.Dockerfile
          push: false
          load: true
          tags: test

      - name: Test
        run: docker run test | grep ^/bin/which$

      - name: Test build the nginx example
        uses: docker/build-push-action@9e436ba9f2d7bcd1d038c8e55d039d37896ddc5d
        with:
          context: .examples/nginx/
          push: false
          load: true
          tags: ng

      - name: Test run nginx example
        run: docker run -p8000:8000 ng && curl 127.0.0.1:8000
